//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THPTChuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        public int MaGiaoVien { get; set; }
        public string TenGiaoVien { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string TotNghiep { get; set; }
        public string ChuyenNganh { get; set; }
        public string CongTacNam { get; set; }
        public Nullable<int> MaChucVu { get; set; }
        public Nullable<int> MaToChuc { get; set; }
        public string avatar { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual ToChuc ToChuc { get; set; }
    }
}
