//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THPTChuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioiThieu
    {
        public int MaGioiThieu { get; set; }
        public string LichSuPhatTrien { get; set; }
        public string NhiemVu { get; set; }
        public string PhanCong { get; set; }
    }
}
