//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THPTChuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanBan
    {
        public int MaVanBan { get; set; }
        public string TieuDe { get; set; }
        public string KiHieu { get; set; }
        public Nullable<System.DateTime> NgayBanHanh { get; set; }
        public Nullable<System.DateTime> NgayHieuLuc { get; set; }
        public Nullable<int> MaLoaiVanBan { get; set; }
        public string NguoiKy { get; set; }
        public string DuongDan { get; set; }
    
        public virtual LoaiVanBan LoaiVanBan { get; set; }
    }
}
